# Pomegranate

Una forma de definir un modelo con HMM utilizando [Pomegranate](http://pomegranate.readthedocs.io/en/latest/index.html). Se define la matriz de transición, las probabilidades de emisión para cada estado y las probabilidades desde el start state hacia los estados y desde los estados hacia el end state.

In [109]:
from pomegranate import *
dists = [NormalDistribution(5, 1), NormalDistribution(1, 7), NormalDistribution(8,2)] #Defino las distribuciones de probabilidades para cada estado
trans_mat = numpy.array([[0.7, 0.3, 0.0],
                             [0.0, 0.8, 0.2],
                             [0.0, 0.0, 0.9]])
starts = numpy.array([1.0, 0.0, 0.0])
ends = numpy.array([0.0, 0.0, 0.1])
model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts, ends)

Una forma de definir lo mismo que en el punto anterior, pero a partir de la topología. model.bake() cierra la definición de la topología.

In [110]:
from pomegranate import *
s1 = State(GeneralMixtureModel( [NormalDistribution(2.5, 1), NormalDistribution(8, 1)] ))
s2 = State(GeneralMixtureModel( [NormalDistribution(5, 1), NormalDistribution(18, 1)] ))
s3 = State(GeneralMixtureModel( [NormalDistribution(7, 1), NormalDistribution(4, 1)] ))
model = HiddenMarkovModel()
model.add_states(s1, s2, s3)
model.add_transition(model.start, s1, 1.0)
model.add_transition(s1, s1, 0.7)
model.add_transition(s1, s2, 0.3)
model.add_transition(s2, s2, 0.8)
model.add_transition(s2, s3, 0.2)
model.add_transition(s3, s3, 0.9)
model.add_transition(s3, model.end, 0.1)
model.bake()

Generemos una realización utilizando el modelo de markov definido anteriormente:

In [111]:
train_set=[model.sample() for i in range(1000)]

In [112]:
dists = [GeneralMixtureModel( [NormalDistribution(1, 1), NormalDistribution(10, 1)] ), GeneralMixtureModel( [NormalDistribution(2, 1), NormalDistribution(20, 1)] ), GeneralMixtureModel( [NormalDistribution(1, 1), NormalDistribution(10, 1)] )]
trans_mat = numpy.array([[0.3, 0.3, 0.4],
                             [0.4, 0.3, 0.3],
                             [0.3, 0.4, 0.4]])
starts = numpy.array([0.3, 0.3, 0.4])
ends = numpy.array([0.4, 0.3, 0.3])
model_train = HiddenMarkovModel.from_matrix(trans_mat, dists, starts, ends)

In [113]:
model_train.dense_transition_matrix()

array([[ 0.21428571,  0.21428571,  0.28571429,  0.        ,  0.28571429],
       [ 0.30769231,  0.23076923,  0.23076923,  0.        ,  0.23076923],
       [ 0.21428571,  0.28571429,  0.28571429,  0.        ,  0.21428571],
       [ 0.3       ,  0.3       ,  0.4       ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [114]:
model_train.fit(train_set)

61697.80478387327

In [117]:
model.dense_transition_matrix()

array([[ 0.8,  0. ,  0.2,  0. ,  0. ],
       [ 0.3,  0.7,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.9,  0. ,  0.1],
       [ 0. ,  1. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ]])

In [118]:
model_train.dense_transition_matrix()

array([[  9.00578404e-001,   8.98003317e-054,   4.80491665e-085,
          0.00000000e+000,   9.94215961e-002],
       [  1.98294543e-001,   8.01705457e-001,   1.89023821e-042,
          0.00000000e+000,   8.52422568e-051],
       [  3.00890132e-020,   3.07898837e-001,   6.92101163e-001,
          0.00000000e+000,   2.08125827e-151],
       [  4.84147264e-050,   3.01761061e-079,   1.00000000e+000,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000]])

Comparemos la matriz obtenida con la matriz generadora del modelo

Veamos los estados y los parámetros de emisión de los mismos:

In [89]:
model_train.states

[{
     "class" : "State",
     "distribution" : {
         "class" : "GeneralMixtureModel",
         "distributions" : [
             {
                 "class" : "Distribution",
                 "name" : "NormalDistribution",
                 "parameters" : [
                     3.9762472955997605,
                     0.9820714925666766
                 ],
                 "frozen" : false
             },
             {
                 "class" : "Distribution",
                 "name" : "NormalDistribution",
                 "parameters" : [
                     6.98256962937187,
                     1.0099371895339044
                 ],
                 "frozen" : false
             }
         ],
         "weights" : [
             -0.7027809419083144,
             -0.6836053436949263
         ]
     },
     "name" : "s0",
     "weight" : 1.0
 }, {
     "class" : "State",
     "distribution" : {
         "class" : "GeneralMixtureModel",
         "distributions" : [
             

In [2]:
from minisom import MiniSom
### Initialization and training ###
X=15
Y=15
som = MiniSom(X,Y,4,sigma=2.5,learning_rate=0.5)

NameError: name 'som' is not defined